---
title: "BLAST ASV counts"
output: html_document
date: "2025-17-01"
---

```{r load libraries}
# setwd("/Users/ekim/Desktop/MMG_ELM/emily_ASV_counts")

library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidyr)
library(viridis)
library(ggforce)
library(concaveman)
```

Load data
```{r load data}
#---------- Load data ----------#
blast_50 <- read.csv("blast_50_ccase.csv")
blast_60 <- read.csv("blast_60_ccase.csv")
blast_70 <- read.csv("blast_60_ccase.csv")
blast_80 <- read.csv("blast_60_ccase.csv")
blast_90 <- read.csv("blast_60_ccase.csv")
mmg_its <- read.csv("ccase_its_w_species.csv")

its_asv <- read.table("ccase_its_asv.txt")
metadata <- read.csv("ccase_its_metadata.csv")

colnames(its_asv) <- its_asv[1,]
its_asv <- its_asv[-1,]
```

Function to get ASV counts for each BLAST method
``` {r load functions}
asv_count_blast <- function(blast_file, its_asv_df, md_df) {
  
  # Filter its_asv_df to only include OTUs that appear in blast_file ASV_ID column
  blast_file <- distinct(blast_file, ASV_ID, .keep_all = TRUE)
  filtered_its_asv <- filter(its_asv_df, OTU %in% blast_file$ASV_ID)
  filtered_its_asv <- subset(filtered_its_asv, select = -c(Soil_119_2))
  its_asv_t <- t(filtered_its_asv)
  its_asv_t <- its_asv_t[-1,]
  its_asv_t <- cbind(JGI.ID = rownames(its_asv_t), its_asv_t)
  its_asv_t <- as.data.frame(its_asv_t)
  
  # Add GOLD IDs to each sample
  its_asv_t <- its_asv_t %>%
    left_join(md_df %>% select(JGI.ID, GOLD.ID), by = "JGI.ID") %>%
    relocate(GOLD.ID)
  
  # Condense by GOLD ID
  its_asv_t <- its_asv_t[, -2]
  its_asv_t <- its_asv_t %>%
    mutate(across(-GOLD.ID, as.numeric))

  blast_file <- aggregate(. ~ GOLD.ID, its_asv_t, sum)
  
  # Count
  blast_file <- blast_file %>%
    mutate(asv_counts = rowSums(across(-GOLD.ID, ~ . > 0))) %>%
    relocate(asv_counts)

  df <- blast_file %>%
    select(c(asv_counts, GOLD.ID))
  
  return(df)
}

asv_count_MMG <- function(its_df, md_df) {
  # Attach GOLD ID
  its_df <- its_df[,-1]
  its_df <- t(its_df)
  its_df <- as.data.frame(its_df)
  its_df$JGI.ID <- row.names(its_df)
  its_df <- its_df %>%
    left_join(md_df %>% select(JGI.ID, GOLD.ID), by = "JGI.ID") %>%
    relocate(GOLD.ID)

  # Aggregate by GOLD ID
  its_df <- its_df[1:(length(its_df)-1)]
  its_df <- aggregate(. ~ GOLD.ID, its_df, sum)
  row.names(its_df) <- its_df$GOLD.ID
  its_df <- its_df[,-1]

  # Count
  its_df$counts <- rowSums(its_df > 0)
  its_df <- its_df %>% relocate(counts)
  
  return(its_df)
}
```

Run functions on datasets
```{r get counts}
blast50_counts <- asv_count_blast(blast_50, its_asv, metadata)
blast60_counts <- asv_count_blast(blast_60, its_asv, metadata)
blast70_counts <- asv_count_blast(blast_70, its_asv, metadata)
blast80_counts <- asv_count_blast(blast_80, its_asv, metadata)
blast90_counts <- asv_count_blast(blast_90, its_asv, metadata)

sp_asv <- mmg_its %>% drop_na(species)
sp_asv <- subset(sp_asv, select = -c(Domain, Phylum, Class, Order, Family, genus))
sp_asv <- sp_asv %>% relocate(species)
## aggregating by species - total 531
# test <- aggregate(. ~ species, sp_asv, sum)
# row.names(test) <- test$species
mmg_sp_counts <- asv_count_MMG(sp_asv, metadata)

gen_asv <- mmg_its %>% drop_na(genus)
gen_asv <- subset(gen_asv, select = -c(Domain, Phylum, Class, Order, Family, species))
gen_asv <- gen_asv %>% relocate(genus)
## aggregating by genus - total 331
# test <- aggregate(. ~ genus, gen_asv, sum)
# row.names(test) <- test$genus
mmg_gen_counts <- asv_count_MMG(test, metadata)
```

Plot pearson graphs - number taxa
```{r plot pearsons - number}
pearsons <- read.csv("Pearsons.csv")
pearsons <- pearsons %>% replace(is.na(.), 0)

c15 <- c(
  "dodgerblue2",
  "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black",
  "gold1",
  "#FB9A99", # lt pink
  "palegreen2",
  "gray70",
  "orchid1",
  "blue1",
  "darkturquoise",
  "yellow4",
  "darkorange4"
)

num_sample <- ggplot(data = pearsons, aes(x = n_taxa_w_genome, y = pearson, color = sample)) +
  geom_point(size = 4) +
  scale_color_manual(values = c15) +
  ggtitle("Pearson correlation vs. Number of taxa assigned a genome - colored by sample") +
  theme_minimal()

num_method <- ggplot(data = pearsons, aes(x = n_taxa_w_genome, y = pearson, color = pred_method)) +
  geom_point(size = 4) +
  scale_color_manual(values = viridis(5)) +
  ggtitle("Pearson correlation vs. Number of taxa assigned a genome - colored by method") +
  theme_minimal()
```

Plot pearson graphs - percent taxa
```{r plot pearsons - percent}
perc_sample <- ggplot(data = pearsons, aes(x = percent_taxa_w_genome, y = pearson, color = sample)) +
  geom_point(size = 4) +
  scale_color_manual(values = c15) +
  ggtitle("Pearson correlation vs. Number of taxa assigned a genome - colored by sample") +
  theme_minimal()

perc_method <- ggplot(data = pearsons, aes(x = percent_taxa_w_genome, y = pearson, color = pred_method)) +
  geom_point(size = 4) +
  scale_color_manual(values = viridis(5)) +
  ggtitle("Pearson correlation vs. Number of taxa assigned a genome - colored by method") +
  theme_minimal()
```