---
title: "R Notebook"
output: html_notebook
---
This script prunes the tips of a tree based on a custom set of tip names.

```{r}
library(ape)
```

Read in the reference trees to do custom tip pruning
```{r}
get_tips <- function(fin, fout) {
  tree <- read.tree(fin)
  tip_labels <- tree$tip.label
  df <- data.frame(tips = tip_labels)
  write.table(df, file = fout, sep = "\n", quote = FALSE, row.names = FALSE, col.names = FALSE)
  
  return(tree)
}

jgi <- get_tips("jgi_modded_alltips.txt", "jgi_tips.csv")
li <- get_tips("li_alltips.nwk", "li_tips.csv")
```

Set tips to delete
```{r}
jgi_tips <- c("Acain1", "Acema1", "Amphiamblys_sp.", "Armga1", "Armost1", "Arnium", "Arxula", "Ascni1", "Aspacu1", "Aspbru1", "Aspcos1", "Aspell1", "Aspergillus_nomius3137_1", "Aspeuc1", "Aspfij1", "Asphet1", "Asphom1", "Aspibe1", "Aspind1", "Aspjap1", "Asplac1", "Aspneo1", "Asppip1", "Asppseute1", "Aspsac1", "Aspscl1", "Aspscle1", "Aspuva1", "Aspvad1", "Aspvio1", "Bimnz1", "Biscogniauxia_sp.", "Cadophora_sp.", "Cadophora_sp.", "Canmem1", "CerAGI", "Cersp1", "Chaetomium_sp.", "Chytriomyces_sp.", "Cladorrhinum_sp.", "Cladorrhinum_sp.", "Coniochaeta_sp.", "Copmar1", "Copmic2", "Coprinopsis_sp.", "Copromyces_sp.", "Cordyceps_sp.", "Crycu1", "Cryte1", "Daldinia_sp.", "Decga1", "Densp1", "Diohu1", "Emericellopsis_sp.", "Endogone_sp", "Erebi1", "Fennellomyces_sp.", "FoxFo5176", "FoxII5", "Fusarium_oxysporum_2", "Fusarium_sp.", "Ganoderma_sp.", "Haplosporangium_sp.", "Haplosporangium_sp.", "Haplosporangium_sp.", "Helsul1", "Hydru2", "Hypoxylon_sp.", "Hypoxylon_sp.", "Hypoxylon_sp.", "Hypoxylon_sp.", "Hypoxylon_sp.", "Hypoxylon_sp.", "Hypoxylon_sp.", "Hypoxylon_sp.", "Hypoxylon_sp.", "Hypoxylon_sp.", "Ilyonectria_sp.", "Ilyonectria_sp.", "Jamsp1", "Lachancea_sp.", "Lacqui1", "Lactifluus_cf.", "Lactifluus_cf.", "Leisp1", "Leotiomycetes_sp.", "Leotiomycetes_sp.", "Leptodontidium_sp.", "Linin1", "Lizem1", "Marfi1", "Maseb1", "Meimi1", "MicG_I_3", "Micmi1", "Morhum1", "Morimp1", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mortierella_sp.", "Mycgal1", "Mycosphaerella", "Mytre1", "Nemania_sp.", "Nemania_sp.", "Nemania_sp.", "Orpinomyces_sp.", "Panru1", "Paxam1", "Pecoramyces_sp.", "Peniophora_sp.", "Perma1", "Pestalotiopsis_sp.", "Phlebopus_sp.", "Phyllosticta_sp.", "Piromyces_sp.", "Pisolithus_sp.", "Pleery1", "Plucer1", "Podospora_aff.", "Polbr1", "Pseudogymnoascus_sp.", "Pseudogymnoascus_sp.", "Pseudogymnoascus_sp.", "Pseudogymnoascus_sp.", "Pseudogymnoascus_sp.", "Pseudogymnoascus_sp.", "Pyrenochaeta_sp.", "Rachicladosporium_sp.", "Rhexocercosporidium_sp.", "Rhihy1", "Rhiir2_1", "RhiirA1_1", "RhiirB3", "RhiirC2", "Rhili1", "Rhodotorula_sp.", "Rhodotorula_sp.", "Rhodsp1", "Ricmel1", "Saccharomycetaceae_sp", "Setho1", "Sistotrema_sp.", "Sorhu1", "Stagonospora_sp.", "Suidec1", "Suigr1", "Suihi1", "Suillus_cf.", "Synps1", "Terbo2", "Termitomyces_sp.", "Tescy1", "Thasp1", "Thega1", "Tilwa1", "Trace1", "Traci1", "Tribi1", "Tubbor1", "Umbelopsis_sp.", "Umbra1", "Ustsp1", "Xerba1", "Xylaria_cf.", "Xylaria_cf.", "Xylaria_sp.", "Xylaria_sp.", "Xylaria_sp.", "Xylaria_sp.", "Xylaria_sp.", "Xylaria_sp.", "Xylariaceae_sp.", "Xylariaceae_sp.", "Xylariaceae_sp.", "Xylariaceae_sp.", "Xylariaceae_sp.", "Xylariaceae_sp.", "Xylariaceae_sp.", "Xylariaceae_sp.", "Xylariaceae_sp.", "Xylariales_sp.", "Xylariomycetidae_sp.", "Xylariomycetidae_sp.", "Yarrowia_lipolytica_1", "Gelatoporia")

li_tips <- c("Gaeumannomyces_sp._JS-464", "Magnaporthe_sp._MG12", "Magnaporthe_sp._MG03", "Magnaporthe_sp._MG07", "Magnaporthe_sp._MG05", "Magnaporthe_sp._MG08", "Raffaelea_sp._RL272", "Juglanconis_sp._DMW523", "Nectria_sp._B-13", "Fusarium_sp._FIESC_12", "Fusarium_sp._FIESC_28", "Fusarium_sp._JS626", "Fusarium_sp._Na10", "Fusarium_sp._FSSC_6", "Fusarium_sp._JS1030", "Epichloe_sp._AL9924", "Tolypocladium_sp._Salcha_MEA-2", "Tolypocladium_sp._Sup5_PDA-1", "Ophiocordyceps_sp._camponoti-leonardi", "Ophiocordyceps_sp._camponoti-saundersi", "Cordyceps_sp._RAO-2017", "Lecanicillium_sp._MT-2017a", "Lecanicillium_sp._LEC01", "Escovopsis_sp._AC", "Escovopsis_sp._Ae724", "Escovopsis_sp._Ae720", "Escovopsis_sp._Ae733", "Escovopsis_sp._TC", "Colletotrichum_sp._JS-367", "Xylaria_sp._MSU_SB201401", "Xylaria_sp._JS573", "Hypoxylon_sp._EC38", "Hypoxylon_sp._CO27-5", "Hypoxylon_sp._E7406B", "Daldinia_sp._EC12", "Hypoxylon_sp._CI-4A", "Pestalotiopsis_sp._JCM_9685", "Cadophora_sp._DSE1049", "Helotiales_sp._F229", "Phialophora_cf._hyalina_BP_5553", "Rutstroemia_sp._NJR-2017a_BBW", "Rutstroemia_sp._NJR-2017a_WRK4", "Rutstroemia_sp._NJR-2017a_BVV2", "Pseudogymnoascus_sp._VKM_F-4515_FW-2607", "Pseudogymnoascus_sp._VKM_F-4517_FW-2822", "Pseudogymnoascus_sp._BL308", "Pseudogymnoascus_sp._23342-1-I1", "Pseudogymnoascus_sp._VKM_F-4520_FW-2644", "Pseudogymnoascus_sp._VKM_F-4518_FW-2643", "Pseudogymnoascus_sp._VKM_F-4281_FW-2241", "Pseudogymnoascus_sp._04NY16", "Pseudogymnoascus_sp._24MN13", "Pseudogymnoascus_sp._VKM_F-103", "Pseudogymnoascus_sp._VKM_F-4519_FW-2642", "Pseudogymnoascus_sp._05NY08", "Pseudogymnoascus_sp._03VT05", "Pseudogymnoascus_sp._WSF_3629", "Pseudogymnoascus_sp._VKM_F-4513_FW-928", "Pseudogymnoascus_sp._VKM_F-4246", "Pseudogymnoascus_sp._BL549", "Pseudogymnoascus_sp._VKM_F-3775", "Pseudogymnoascus_sp._VKM_F-4516_FW-969", "Pseudogymnoascus_sp._VKM_F-4514_FW-929", "Pseudogymnoascus_sp._VKM_F-3557", "Pseudogymnoascus_sp._VKM_F-3808", "Wickerhamomyces_sp._YB_2243", "Crepidotus_sp._BD2015", "Tricholoma_sp._MG99", "Tricholoma_sp._MG77", "Termitomyces_sp._MG16", "Termitomyces_sp._MG148", "Termitomyces_sp._J132", "Termitomyces_sp._MG145", "Termitomyces_sp._JCM_13351", "Collybia_sp._MG36", "Leucoagaricus_sp._SymC.cos", "Agaricales_sp._HM26F1", "Fibularhizoctonia_sp._CBS_109695", "Boletus_sp._MG95", "Boletus_sp._MG55", "Suillus_sp._MG131", "Rhizopogon_sp._AM2018a", "Ganoderma_sp._BRIUMSc", "Trametes_sp._AH282", "Sarcodon_sp._MG97", "Lactarius_sp._MG50", "Russula_sp._MG48", "Lactarius_sp._MG121", "Peniophora_sp._CONT", "Peniophora_sp._CBMAI_1063", "Dentipellis_sp._KUC8613", "Albatrellus_sp._MG142", "Ramaria_sp._MG151", "Gomphus_sp._MG54", "Ramaria_cf._rubripermanens", "Cryptococcus_cf._gattii", "Cryptococcus_sp._DSM_27421", "Cryptococcus_sp._JCM_24511", "Pseudozyma_sp._F8B2", "Moesziomyces_sp._F16C1", "Moesziomyces_sp._F5C1", "Malassezia_sp.", "Moniliella_sp._wahieum", "Rhodotorula_sp._CCFEE_5036", "Rhodotorula_sp._JG1b", "Rhodotorula_sp._FNED722", "Gongronella_sp._w5", "Endogone_sp._FLASF59071", "Rhizophagus_sp._MUCL_43196", "Zoopage_sp._CTAll", "Ichthyosporea_sp._XGB_2017a", "Nematocida_sp._ERTm5", "Nematocida_sp._1", "Amphiamblys_sp._WSBS2006", "Spizellomyces_sp._palustris", "Piromyces_sp._E2", "Curvularia_sp._IFB-Z10", "Pyrenochaeta_sp._DS3sAY3a", "Pyrenochaeta_sp._UM_256", "Shiraia_sp._slf14", "Paraphoma_sp._B47-9", "Pleosporales_sp._UM_1110_2012", "Stagonospora_sp._SRC1lsM3a", "Rachicladosporium_sp._CCFEE_5018", "Cladosporium_sp._SL-16", "Preussia_sp._BSL10", "Mycosphaerella_sp._PB-2012b", "Mycosphaerella_sp._Ston1", "Cercospora_cf._sigesbeckiae", "Aureobasidium_sp._FSWF8-4", "Eurotiomycetes_sp.", "Herpotrichiellaceae_sp._UM238", "Blastomyces_sp._MA-2018", "Emmonsia_sp._CAC-2015a", "Byssochlamys_sp._BYSS01", "Aspergillus_sp._Z5", "Aspergillus_sp._MA_6037", "Eurotiomycetes_sp._MA_6039", "Eurotiomycetes_sp._MA_6038", "Penicillium_sp._MA_6040", "Penicillium_sp._HKF2", "Penicillium_sp._CF05", "Penicillium_sp._MA_6036", "Byssochlamys_sp._AF001")
```

Delete tips
```{r}
prune_tips <- function(tree, tips, fout) {
  new_tree <- drop.tip(tree, tips)
  write.tree(new_tree, fout)
}

prune_tips(jgi, jgi_tips, "jgi_half_pruned.txt")
prune_tips(li, li_tips, "Lietal_2021.nwk")
```